version: "3"
services:
  app:
    image: gabrielcamurcab/finance
    container_name: "app_finance_go"
    ports:
      - 8080:8080
    networks:
      - minha-rede

networks:
  minha-rede:
    external: true
