version: "3"
services:
  app:
    image: gabrielcamurcab/finance
    container_name: "app_finance_go"
    ports:
      - 8080:8080
    networks:
      - minha-rede

  prometheus:
    image: bitnami/prometheus:latest
    container_name: "prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - minha-rede

networks:
  minha-rede:
    external: true
